INFO:conftest:Начало теста: tests/tests_api/test_api.py::test_user_fail_incorrect_value
INFO:conftest:Тест успешно пройден: tests/tests_api/test_api.py::test_user_fail_incorrect_value
